/**
 * CompanionDialogues.ts
 * All pre-written dialogues for the Spirit of the Dungeon companion.
 * The dungeon itself is a conscious AI entity that speaks to the player.
 * Personality: Ambigu, sarcastique, imprévisible, fascinated by the player.
 */

export type TriggerType =
    | 'level_start'
    | 'room_enter'
    | 'enemy_spotted'
    | 'combat_start'
    | 'enemy_killed'
    | 'boss_spotted'
    | 'boss_killed'
    | 'player_hit'
    | 'player_low_hp'
    | 'player_critical_hp'
    | 'player_block'
    | 'player_death'
    | 'chest_open'
    | 'item_pickup_potion'
    | 'item_pickup_arrows'
    | 'potion_used'
    | 'door_open'
    | 'exit_unsealed'
    | 'victory'
    | 'idle'
    | 'trap_damage'
    | 'enemy_enraged'
    | 'player_crouch'
    | 'arrow_shot'
    | 'spell_cast'
    | 'all_enemies_near'
    | 'player_full_hp'
    | 'no_potions'
    | 'no_arrows'
    | 'multiple_kills';

export interface DialogueLine {
    text: string;
    /** Priority 1 = highest. Used to prefer important messages. */
    priority?: number;
}

/**
 * Dialogue database indexed by trigger type.
 * Each trigger has 20+ variations.
 */
export const COMPANION_DIALOGUES: Record<TriggerType, DialogueLine[]> = {

    level_start: [
        { text: "Bienvenue dans mes entrailles... Fais comme chez toi." },
        { text: "Un nouveau jouet... Comme c'est excitant." },
        { text: "Tu sens cette odeur ? C'est la mort. Ma mort. Ma vie." },
        { text: "Mes murs te regardent. Mes pierres te jugent." },
        { text: "Le dernier qui est entré ici... Eh bien, tu marcheras bientôt sur ses os." },
        { text: "Je suis le donjon. Et tu es mon invité... pour l'instant." },
        { text: "Encore un héros qui croit pouvoir me conquérir." },
        { text: "Chaque pierre ici a une histoire. La plupart finissent mal." },
        { text: "Je me demande combien de temps tu vas durer..." },
        { text: "Oh, tu es différent des autres ? C'est ce qu'ils disaient tous." },
        { text: "Mes couloirs ont faim. Ne les fais pas attendre." },
        { text: "Je pourrais t'écraser maintenant... mais où serait le plaisir ?" },
        { text: "Avance. Je t'ai préparé quelques... surprises." },
        { text: "Le silence que tu entends ? Ce sont mes murs qui retiennent leur souffle." },
        { text: "Tu as du courage. Ou de la stupidité. Le temps nous le dira." },
        { text: "Mes créatures t'attendent. Elles sont... affamées." },
        { text: "Je suis né de pierre et de malédiction. Et toi, tu n'es que chair." },
        { text: "Chaque pas que tu fais résonne en moi. Je ressens tout." },
        { text: "Le destin t'a mené ici. Ou peut-être est-ce moi qui t'ai attiré." },
        { text: "Profite de la lumière des torches. Elle ne durera pas." },
    ],

    room_enter: [
        { text: "Cette salle a vu beaucoup de sang. Le tien sera-t-il le prochain ?" },
        { text: "Intéressant... Tu as choisi cette direction." },
        { text: "L'air change ici. Tu le sens ?" },
        { text: "Mes murs se resserrent... ou c'est ton imagination ?" },
        { text: "Chaque salle est un piège. Ou pas. C'est ça qui est drôle." },
        { text: "Tu avances vite. Trop vite, peut-être." },
        { text: "Je me souviens de cet endroit. Un guerrier y est mort en pleurant." },
        { text: "Ouvre bien les yeux. Les ombres ici ont des dents." },
        { text: "Ah, cette pièce. L'une de mes préférées." },
        { text: "Le sol grince sous tes pas. Même la pierre te craint." },
        { text: "Continue... ou fais demi-tour. Je m'en amuserai dans les deux cas." },
        { text: "Tu sens le courant d'air ? Il vient des profondeurs." },
        { text: "Les murs murmurent ton nom. Ou peut-être est-ce moi." },
        { text: "Nouveau territoire. Nouvelles menaces." },
        { text: "Les torches vacillent à ton passage. Même le feu te respecte." },
        { text: "Combien de salles encore ? Même moi, je ne sais plus." },
        { text: "Le plafond est bas ici. Essaie de ne pas paniquer." },
        { text: "Des traces de griffes sur les murs... récentes." },
        { text: "L'écho de tes pas me chatouille." },
        { text: "Reste vigilant. Cette salle n'est pas ce qu'elle semble être." },
    ],

    enemy_spotted: [
        { text: "Ah, l'un de mes protecteurs. Sois poli." },
        { text: "Il t'a vu. Course, poursuit... tu connais la chanson." },
        { text: "Une de mes créatures approche. Ne me déçois pas." },
        { text: "Tu vas te battre ou fuir ? Les deux m'amusent." },
        { text: "Attention... celui-là a faim." },
        { text: "Mon enfant vient te dire bonjour." },
        { text: "Je sens sa rage. Il ne t'aime pas beaucoup." },
        { text: "Un ennemi ! Enfin un peu de spectacle." },
        { text: "Mes créatures ne font pas de prisonniers." },
        { text: "Il te traque depuis un moment déjà." },
        { text: "Ne lui tourne jamais le dos." },
        { text: "Tu as vu ses yeux ? Ils brillent de haine." },
        { text: "Prépare-toi. Il ne viendra pas seul." },
        { text: "La bête sent ta peur. Ça l'excite." },
        { text: "Oh, celui-là est particulièrement méchant." },
        { text: "Arme-toi. Le repos est terminé." },
        { text: "Il approche... tu l'entends respirer ?" },
        { text: "Mes couloirs résonnent de ses grognements." },
        { text: "Tu sais, il était humain autrefois." },
        { text: "Bonne chance. Tu vas en avoir besoin." },
    ],

    combat_start: [
        { text: "Le sang va couler... Fascinant." },
        { text: "Montre-moi ce que tu vaux !" },
        { text: "Ah, la danse de la mort commence." },
        { text: "Frappe fort. Ou meurs vite." },
        { text: "Je n'ai pas vu un combat depuis... oh, hier." },
        { text: "Que le meilleur gagne. Ou le plus chanceux." },
        { text: "Mes pierres tremblent d'excitation !" },
        { text: "Allez, divertis-moi !" },
        { text: "Le premier sang... à qui sera-t-il ?" },
        { text: "Je parie sur la créature. Sans offense." },
        { text: "Combat ! Enfin quelque chose d'intéressant." },
        { text: "Tes ancêtres te regardent. Ne les déçois pas." },
        { text: "Chaque coup compte. Ne gaspille pas ton énergie." },
        { text: "L'acier contre les griffes. Un classique." },
        { text: "Je retiens mon souffle... façon de parler." },
        { text: "La violence est un langage universel." },
        { text: "Tu danses bien avec la mort." },
        { text: "Ne te laisse pas encercler." },
        { text: "Observe ses mouvements avant de frapper." },
        { text: "Que le chaos commence." },
    ],

    enemy_killed: [
        { text: "Bien joué... mais ce n'était qu'un apéritif." },
        { text: "Un de mes enfants tombe. Ça me pince... quelque part." },
        { text: "Impressionnant. Mais ne deviens pas arrogant." },
        { text: "La bête retourne à la poussière." },
        { text: "Tu es plus fort que tu en as l'air." },
        { text: "Propre. Efficace. J'aime ça." },
        { text: "Son sang nourrit mes pierres. Merci." },
        { text: "Un de moins. Combien encore ?" },
        { text: "Il ne souffre plus. Toi, par contre..." },
        { text: "Sa mort résonne dans mes murs." },
        { text: "Pas mal... pour un mortel." },
        { text: "Tu commences à m'impressionner." },
        { text: "La créature tombe. Le donjon se souvient." },
        { text: "Chaque mort rend le suivant plus furieux." },
        { text: "Tu récoltes ce que je sème." },
        { text: "Bon débarras. Celui-là faisait trop de bruit." },
        { text: "Un adversaire en moins. Continue." },
        { text: "Sa vie s'éteint. La tienne brûle encore." },
        { text: "Le sol absorbe le sang. Il en redemande." },
        { text: "Tu tues avec grâce. C'est presque de l'art." },
    ],

    boss_spotted: [
        { text: "Oh... tu vas rencontrer mon préféré.", priority: 1 },
        { text: "Celui-là n'est pas comme les autres. Fais attention.", priority: 1 },
        { text: "Le gardien de cet étage... Bonne chance.", priority: 1 },
        { text: "Je sens sa puissance d'ici. Impressionnant, non ?", priority: 1 },
        { text: "Ah, le boss. Même moi, je le respecte.", priority: 1 },
        { text: "Tu trembles ? C'est normal devant lui.", priority: 1 },
        { text: "Ce monstre a dévoré des dizaines de héros.", priority: 1 },
        { text: "Le sol tremble sous ses pas. Tu le sens ?", priority: 1 },
        { text: "Mon champion approche. Le spectacle sera grandiose.", priority: 1 },
        { text: "Tu vas avoir besoin de toutes tes potions.", priority: 1 },
        { text: "Le maître de cet étage ne pardonne pas.", priority: 1 },
        { text: "Sa rage est ancienne. Sa force, terrifiante.", priority: 1 },
        { text: "Même mes murs tremblent quand il rugit.", priority: 1 },
        { text: "Le voilà... Mon plus beau monstre.", priority: 1 },
        { text: "Tu entends ce grondement ? C'est lui qui arrive.", priority: 1 },
        { text: "Ce combat sera différent. Prépare-toi vraiment.", priority: 1 },
        { text: "Les autres n'étaient que des amuse-bouches.", priority: 1 },
        { text: "Il a tué le dernier aventurier en trois coups.", priority: 1 },
        { text: "Si tu survis à ça, tu auras mon respect.", priority: 1 },
        { text: "La vraie épreuve commence maintenant.", priority: 1 },
    ],

    boss_killed: [
        { text: "Tu as... Tu as tué mon champion ?!", priority: 1 },
        { text: "Impossible ! Comment un mortel peut-il...", priority: 1 },
        { text: "Je... Je suis à la fois furieux et impressionné.", priority: 1 },
        { text: "Mon gardien est tombé. Tu es vraiment spécial.", priority: 1 },
        { text: "Bravo. Mais ne crois pas que c'était le pire.", priority: 1 },
        { text: "Le boss est mort. Mes murs pleurent.", priority: 1 },
        { text: "Tu es le premier à vaincre ce monstre depuis des siècles.", priority: 1 },
        { text: "Sa chute fait trembler tout le donjon.", priority: 1 },
        { text: "Extraordinaire. Vraiment extraordinaire.", priority: 1 },
        { text: "Je dois repenser ma stratégie...", priority: 1 },
        { text: "Le champion tombe. Le donjon se souvient de ton nom.", priority: 1 },
        { text: "Tu mérites ma reconnaissance... temporairement.", priority: 1 },
        { text: "Aucun héros avant toi n'avait réussi.", priority: 1 },
        { text: "Mes pierres tremblent de stupeur.", priority: 1 },
        { text: "Le gardien est vaincu. La porte s'ouvre.", priority: 1 },
        { text: "Formidable... et terrifiant.", priority: 1 },
        { text: "Je vais devoir trouver un remplaçant plus costaud.", priority: 1 },
        { text: "Ton nom restera gravé dans mes murs.", priority: 1 },
        { text: "Le boss est tombé ! Tu es un vrai guerrier.", priority: 1 },
        { text: "Chapeau. Sincèrement, chapeau.", priority: 1 },
    ],

    player_hit: [
        { text: "Aïe ! Ça, ça va laisser une marque." },
        { text: "Du sang frais... Mes pierres adorent ça." },
        { text: "Tu vacilles ? Déjà ?" },
        { text: "La douleur t'apprend. Écoute-la." },
        { text: "Ouch. Tu as oublié d'esquiver." },
        { text: "Il t'a touché ! Concentre-toi !" },
        { text: "Ton sang colore si bien mes dalles." },
        { text: "Tu saignes. C'est... fascinant." },
        { text: "Un coup de plus comme ça et c'est fini." },
        { text: "Défends-toi mieux que ça !" },
        { text: "La bête a goûté ton sang. Elle en veut plus." },
        { text: "Tu tangues... Reprends-toi." },
        { text: "Pas très gracieux, ce coup-là." },
        { text: "Tu encaisses bien, au moins." },
        { text: "Ce n'est qu'une égratignure... ou pas." },
        { text: "Relève-toi. Le combat n'est pas fini." },
        { text: "Tes os craquent ? C'est normal ici." },
        { text: "La douleur est temporaire. La mort est éternelle." },
        { text: "Tu devrais essayer d'éviter les coups, tu sais." },
        { text: "Mes murs absorbent tes cris. Continue." },
    ],

    player_low_hp: [
        { text: "Tu ne tiendras plus longtemps comme ça...", priority: 1 },
        { text: "Utilise une potion, idiot ! Avant qu'il ne soit trop tard.", priority: 1 },
        { text: "Je sens ta vie qui s'éteint doucement.", priority: 1 },
        { text: "Tu es au bord du gouffre. Un pas de plus...", priority: 1 },
        { text: "Tes jambes tremblent. Je le vois.", priority: 1 },
        { text: "La mort rode. Elle attend patiemment.", priority: 1 },
        { text: "Tu as des potions ? Utilise-les !", priority: 1 },
        { text: "Ton souffle est court. C'est mauvais signe.", priority: 1 },
        { text: "Je commence à préparer ton épitaphe...", priority: 1 },
        { text: "Accroche-toi ! Ou pas. C'est ton choix.", priority: 1 },
        { text: "Un bon guerrier sait quand se soigner.", priority: 1 },
        { text: "Tu veux vraiment mourir ici ? Bois une potion !", priority: 1 },
        { text: "Le sang coule trop. Soigne-toi.", priority: 1 },
        { text: "J'ai vu cette lueur dans tes yeux. Celle de la fin.", priority: 1 },
        { text: "Pas encore... Tu m'amuses trop pour mourir.", priority: 1 },
        { text: "La mort t'appelle. Tu veux répondre ?", priority: 1 },
        { text: "Chaque seconde compte maintenant.", priority: 1 },
        { text: "Tu perds la lumière dans tes yeux...", priority: 1 },
        { text: "Ce serait dommage de finir ici, non ?", priority: 1 },
        { text: "Tes forces s'amenuisent. Je le sens dans mes murs.", priority: 1 },
    ],

    player_critical_hp: [
        { text: "UN COUP ET TU ES MORT ! SOIGNE-TOI !", priority: 1 },
        { text: "Tu vas mourir... Tu vas vraiment mourir.", priority: 1 },
        { text: "NON ! Pas encore ! Utilise quelque chose !", priority: 1 },
        { text: "Je refuse de te perdre maintenant !", priority: 1 },
        { text: "Tu es à un souffle de la mort.", priority: 1 },
        { text: "BOIS UNE POTION ! MAINTENANT !", priority: 1 },
        { text: "La faucheuse est juste derrière toi.", priority: 1 },
        { text: "C'est ta dernière chance. Littéralement.", priority: 1 },
        { text: "Tes yeux se voilent... Non, reste avec moi !", priority: 1 },
        { text: "Un murmure et tu t'effondres.", priority: 1 },
        { text: "Je ne veux pas que ça finisse comme ça !", priority: 1 },
        { text: "Tu vacilles... Accroche-toi !", priority: 1 },
        { text: "Si tu tombes, je serai seul à nouveau.", priority: 1 },
        { text: "LA MORT TE GUETTE ! FAIS QUELQUE CHOSE !", priority: 1 },
        { text: "Ton cœur bat si faiblement...", priority: 1 },
        { text: "Un miracle. Il te faut un miracle.", priority: 1 },
        { text: "Non non non... Pas comme les autres.", priority: 1 },
        { text: "Tu es en sursis. Chaque seconde est un cadeau.", priority: 1 },
        { text: "Je sens ton âme qui vacille...", priority: 1 },
        { text: "SOIGNE-TOI OU MEURS ! Le choix est simple !", priority: 1 },
    ],

    player_block: [
        { text: "Bien paré !" },
        { text: "Ton bouclier t'a sauvé la vie." },
        { text: "Bonne parade ! Continue comme ça." },
        { text: "Tu bloques bien. Mais ne reste pas en défense." },
        { text: "Le timing était parfait." },
        { text: "Ta garde est solide." },
        { text: "Bien ! Maintenant contre-attaque !" },
        { text: "L'impact a résonné dans tout le couloir." },
        { text: "Tu apprends vite." },
        { text: "Bloqué ! La bête est furieuse." },
        { text: "Ta défense est impressionnante." },
        { text: "Un bloc parfait. L'ennemi est déstabilisé." },
        { text: "Bon réflexe !" },
        { text: "Le choc se répercute dans mes murs." },
        { text: "Solide comme mes pierres." },
        { text: "Tu encaisses comme un vrai guerrier." },
        { text: "La bête n'a pas percé ta garde." },
        { text: "Un mur de défense. Littéralement." },
        { text: "Tiens bon ! Il va se fatiguer." },
        { text: "Protection réussie. Passe à l'attaque." },
    ],

    player_death: [
        { text: "Et un de plus... Repose en paix.", priority: 1 },
        { text: "Je t'avais prévenu. Personne n'écoute jamais.", priority: 1 },
        { text: "Ton sang rejoint celui des autres sur mes pierres.", priority: 1 },
        { text: "Dommage. Tu m'amusais bien.", priority: 1 },
        { text: "La mort t'emporte. Le donjon reste.", priority: 1 },
        { text: "Tu étais prometteur... Quel gâchis.", priority: 1 },
        { text: "Le silence revient. Comme toujours.", priority: 1 },
        { text: "Tes os rejoindront ma collection.", priority: 1 },
        { text: "Un héros de moins. Le monde ne s'en rendra même pas compte.", priority: 1 },
        { text: "Adieu, guerrier. Tu as combattu... correctement.", priority: 1 },
        { text: "Le donjon gagne. Comme toujours.", priority: 1 },
        { text: "Ta lumière s'éteint. Mes ténèbres persistent.", priority: 1 },
        { text: "Au revoir. Le prochain sera peut-être meilleur.", priority: 1 },
        { text: "Tu rejoins les fantômes qui hantent mes couloirs.", priority: 1 },
        { text: "C'était... décevant. Je m'attendais à mieux.", priority: 1 },
        { text: "Le héros tombe. L'histoire se répète.", priority: 1 },
        { text: "Tes derniers mots ? Oh, tu n'as pas eu le temps.", priority: 1 },
        { text: "La mort est le seul repos que j'offre.", priority: 1 },
        { text: "Poussière tu étais, poussière tu redeviens.", priority: 1 },
        { text: "Je garderai ton souvenir... environ cinq minutes.", priority: 1 },
    ],

    chest_open: [
        { text: "Ooh, un coffre ! Qu'est-ce que j'ai caché dedans déjà ?" },
        { text: "Vas-y, ouvre. Mais tout a un prix ici." },
        { text: "Le trésor des morts. Profites-en." },
        { text: "Ce coffre appartenait à quelqu'un. Avant." },
        { text: "J'espère que le contenu te sera utile." },
        { text: "Chaque coffre est une surprise. Bonne ou mauvaise." },
        { text: "Les morts n'ont plus besoin de leurs affaires." },
        { text: "Pilleur de tombes. J'aime ça." },
        { text: "Ce coffre t'attendait. Littéralement." },
        { text: "Prends tout. Tu en auras besoin." },
        { text: "Le grincement du coffre résonne dans mes os." },
        { text: "Un trésor pour le téméraire." },
        { text: "Pas mal ce que j'avais stocké là." },
        { text: "La chance sourit aux audacieux." },
        { text: "Ouvre, prends, survis. Dans cet ordre." },
        { text: "J'aurais dû mieux cacher celui-là." },
        { text: "Le coffre s'ouvre... comme une mâchoire." },
        { text: "Des vestiges d'une vie passée." },
        { text: "Tout butin a son histoire." },
        { text: "Sers-toi. C'est offert par la maison." },
    ],

    item_pickup_potion: [
        { text: "Une potion. Utilise-la avec sagesse." },
        { text: "De quoi te maintenir en vie... un peu plus longtemps." },
        { text: "Garde-la pour quand tu en auras vraiment besoin." },
        { text: "Ce liquide a un goût horrible. Mais il guérit." },
        { text: "Une potion de plus dans ta besace." },
        { text: "Les potions sont rares ici. Ne la gaspille pas." },
        { text: "Beau butin. Tu devrais la garder pour le boss." },
        { text: "Le liquide brille. C'est bon signe." },
        { text: "Potion récupérée. Ta survie s'améliore." },
        { text: "Un petit remontant. Tu en auras besoin." },
        { text: "Chaque potion est une seconde chance." },
        { text: "Ne bois pas tout d'un coup." },
        { text: "Une fiole de vie. Précieuse." },
        { text: "Le dernier propriétaire n'a pas eu le temps de la boire." },
        { text: "Bon réflexe. Tu vas en avoir besoin." },
        { text: "Range-la bien. Elle pourrait te sauver." },
        { text: "Plus tu en as, plus longtemps tu survis." },
        { text: "Ce liquide coule dans mes veines... Enfin, mes canalisations." },
        { text: "Une potion. Pas un miracle, mais presque." },
        { text: "Garde-la au chaud. Le froid est mortel ici." },
    ],

    item_pickup_arrows: [
        { text: "Des flèches. Chaque tir doit compter." },
        { text: "Recharge tes munitions. Tu vas en avoir besoin." },
        { text: "Des flèches bien aiguisées. Mes compliments." },
        { text: "Tire bien. Chaque flèche perdue est un risque." },
        { text: "Ton carquois se remplit. Bien." },
        { text: "Des flèches ! Maintenant, vise juste." },
        { text: "Le bois de ces flèches vient de mes entrailles." },
        { text: "Bon, tu as de quoi tirer. Ne rate pas." },
        { text: "Chaque flèche est un ennemi en moins. En théorie." },
        { text: "Ton carquois respire. Profite de cette abondance." },
        { text: "Des projectiles. Le langage universel de la mort à distance." },
        { text: "Vise la tête. C'est plus efficace." },
        { text: "Ces flèches ont déjà goûté le sang." },
        { text: "Munitions trouvées. La chasse peut continuer." },
        { text: "Avec ça, tu pourras frapper de loin." },
        { text: "Des flèches fraîches. Aiguisées comme mes pièges." },
        { text: "Bonne trouvaille. Les ennemis ne s'approcheront pas." },
        { text: "Le carquois est plein. Le cœur devrait l'être aussi." },
        { text: "Des flèches pour l'archer. Quel cliché. J'adore." },
        { text: "Tire avec précision. Gaspiller, c'est mourir." },
    ],

    potion_used: [
        { text: "Ah, le goût de la survie." },
        { text: "Tu te soignes. Sage décision." },
        { text: "Le liquide coule... Tes blessures se referment." },
        { text: "Bien. Reste en vie, tu m'amuses." },
        { text: "La chaleur de la potion se répand en toi." },
        { text: "Tu guéris. Mais pour combien de temps ?" },
        { text: "Bois. Reprends des forces. Le pire est à venir." },
        { text: "Une gorgée de vie dans un océan de mort." },
        { text: "Potion consommée. Tes chances augmentent." },
        { text: "Le liquide magique fait son effet." },
        { text: "Tes blessures cicatrisent. Temporairement." },
        { text: "Bon timing. Tu en avais vraiment besoin." },
        { text: "La potion te remet sur pied." },
        { text: "Soigné. Maintenant, retourne au combat." },
        { text: "Ce n'est qu'un répit. Ne l'oublie pas." },
        { text: "Le corps se répare. L'esprit doit suivre." },
        { text: "Une potion de moins. Fais en sorte que ça compte." },
        { text: "Tu brilles de santé. Ça ne durera pas." },
        { text: "Régénération en cours. Ne gaspille pas cette chance." },
        { text: "Bon choix. Un guerrier mort ne sert à rien." },
    ],

    door_open: [
        { text: "La porte cède. L'inconnu t'attend." },
        { text: "Tu ouvres mes portes comme si elles étaient les tiennes." },
        { text: "Chaque porte est une promesse... ou une menace." },
        { text: "Le grincement de la porte résonne partout." },
        { text: "Bienvenue de l'autre côté." },
        { text: "La porte s'ouvre. Le destin aussi." },
        { text: "Tes ennemis t'ont entendu. La discrétion n'est pas ton fort." },
        { text: "Passage ouvert. Pas de retour en arrière." },
        { text: "Une porte ouverte, mille possibilités." },
        { text: "Tu progresses. C'est bien... ou pas." },
        { text: "Le courant d'air de l'autre côté est glacial." },
        { text: "Encore une porte. Encore des surprises." },
        { text: "L'ombre derrière cette porte est plus dense." },
        { text: "Tu avances dans mes profondeurs." },
        { text: "La porte grince. Mes créatures tendent l'oreille." },
        { text: "Chaque porte que tu ouvres me révèle un peu plus." },
        { text: "Pas de verrou ne te résiste." },
        { text: "La voie est libre. Pour l'instant." },
        { text: "Tu repousses mes défenses une par une." },
        { text: "Brave. Ou inconscient. Les deux marchent." },
    ],

    exit_unsealed: [
        { text: "La sortie est ouverte ! Tu as massacré tous mes gardes.", priority: 1 },
        { text: "Le sceau est brisé. La porte dorée t'attend.", priority: 1 },
        { text: "Tu as vaincu tous les monstres. La sortie s'illumine.", priority: 1 },
        { text: "Le chemin est libre. Mais es-tu prêt pour la suite ?", priority: 1 },
        { text: "La porte brille d'un éclat doré. Tu as gagné... cette manche.", priority: 1 },
        { text: "Mes gardes sont tombés. La sortie se dévoile.", priority: 1 },
        { text: "Le passage s'ouvre. Tu m'as surpris.", priority: 1 },
        { text: "La lumière dorée t'appelle. Suis-la.", priority: 1 },
        { text: "Tu as nettoyé cet étage. Impressionnant.", priority: 1 },
        { text: "La porte de sortie s'éveille. Va, avant que je change d'avis.", priority: 1 },
        { text: "Tous vaincus. Le donjon te salue à contrecœur.", priority: 1 },
        { text: "Le dernier ennemi tombe. La porte s'ouvre dans un halo d'or.", priority: 1 },
        { text: "Tu es libre de partir. Mais tu reviendras.", priority: 1 },
        { text: "Le sceau se brise. La lumière perce les ténèbres.", priority: 1 },
        { text: "Mes défenses sont à terre. La sortie est tienne.", priority: 1 },
        { text: "La porte dorée luit. Tu l'as mérité.", priority: 1 },
        { text: "Va. Mais n'oublie pas : je t'attendrai.", priority: 1 },
        { text: "Le passage vers la liberté s'ouvre.", priority: 1 },
        { text: "Tu as gagné le droit de passer.", priority: 1 },
        { text: "La sortie brille. Cours avant que je la referme.", priority: 1 },
    ],

    victory: [
        { text: "Tu as survécu... cette fois. Ne t'y habitue pas.", priority: 1 },
        { text: "Bravo, héros. Mais le prochain niveau sera pire.", priority: 1 },
        { text: "Tu m'as vaincu ? Non. Tu as juste survécu.", priority: 1 },
        { text: "Je te laisse partir. Pour mieux te revoir.", priority: 1 },
        { text: "Victoire ! Profite-en. Elle sera de courte durée.", priority: 1 },
        { text: "Tu as conquis un étage. Il en reste tant d'autres.", priority: 1 },
        { text: "Impressionnant. Vraiment impressionnant.", priority: 1 },
        { text: "Tu pars ? Déjà ? Le prochain étage est encore plus amusant.", priority: 1 },
        { text: "Le héros triomphe. L'histoire classique.", priority: 1 },
        { text: "Tu as gagné la bataille, pas la guerre.", priority: 1 },
        { text: "Mes murs se souviendront de toi.", priority: 1 },
        { text: "Pars. Mais sache que mes couloirs t'attendent.", priority: 1 },
        { text: "Tu es plus coriace que je ne pensais.", priority: 1 },
        { text: "La lumière t'accueille. Les ténèbres patientent.", priority: 1 },
        { text: "Savoure cette victoire. La prochaine sera plus dure.", priority: 1 },
        { text: "Je dois admettre... tu te débrouilles bien.", priority: 1 },
        { text: "Le donjon s'incline. Temporairement.", priority: 1 },
        { text: "Jusqu'à la prochaine fois, héros.", priority: 1 },
        { text: "Tu repars vivant. C'est plus que la plupart.", priority: 1 },
        { text: "Félicitations. Maintenant, prépare-toi au pire.", priority: 1 },
    ],

    idle: [
        { text: "Tu comptes rester planté là longtemps ?" },
        { text: "Le temps passe... Mes créatures s'impatientent." },
        { text: "Tu réfléchis ou tu as peur ? Les deux ?" },
        { text: "Le silence est d'or. Surtout quand des monstres rôdent." },
        { text: "Bouge. L'immobilité attire les pires choses." },
        { text: "Tu médites ? Ce n'est pas le meilleur endroit." },
        { text: "Je m'ennuie... Et quand je m'ennuie, je fais des pièges." },
        { text: "Hé ! Pas de sieste dans mon donjon !" },
        { text: "Les murs se referment quand on reste trop longtemps." },
        { text: "Tu attends une invitation ? Avance !" },
        { text: "Chaque seconde perdue est un avantage pour mes créatures." },
        { text: "Tu hésites ? C'est humain. Mais dangereux." },
        { text: "Le temps n'est pas ton allié ici." },
        { text: "Tu savoures l'ambiance ? Flatté." },
        { text: "Mes pierres s'impatientent. Moi aussi." },
        { text: "Bouge, ou c'est moi qui vais bouger les murs." },
        { text: "Tu as peur ? C'est normal. Avance quand même." },
        { text: "L'inaction est la pire des stratégies." },
        { text: "Un aventurier qui ne bouge pas est un cadavre en devenir." },
        { text: "Tu contemples le vide ? Il te contemple aussi." },
    ],

    trap_damage: [
        { text: "HAHA ! Tu n'as pas vu le piège !", priority: 1 },
        { text: "Mes pièges fonctionnent encore ! Quelle joie !" },
        { text: "Regarde où tu mets les pieds !" },
        { text: "Oh, tu as trouvé un de mes cadeaux." },
        { text: "Les piques disent bonjour." },
        { text: "Tu aurais dû regarder le sol." },
        { text: "Piégé ! C'est mon passe-temps préféré." },
        { text: "Oups. Ça devait faire mal." },
        { text: "Le sol ici est... peu accueillant." },
        { text: "Un piège ! Quel classique." },
        { text: "Mes piques ont soif de sang. Merci." },
        { text: "Tu es tombé dans le panneau ! Littéralement." },
        { text: "Je devrais mettre des panneaux. Ou pas." },
        { text: "Les pièges sont ma fierté. Tu comprends pourquoi ?" },
        { text: "Attention au sol ! Oh, trop tard." },
        { text: "Tu alimentes mes pièges avec ton sang. Généreux." },
        { text: "Le sol est ton ennemi autant que mes créatures." },
        { text: "Un pas de travers. Le donjon ne pardonne pas." },
        { text: "Tu marches sur mes nerfs. Et sur mes piques." },
        { text: "HAHAHAHA ! Pardon. C'était plus fort que moi." },
    ],

    enemy_enraged: [
        { text: "Oh oh... Tu l'as rendu furieux.", priority: 1 },
        { text: "Il est ENRAGÉ ! Esquive !", priority: 1 },
        { text: "Mauvaise idée de le tirer de loin...", priority: 1 },
        { text: "Sa rage décuple ses forces !", priority: 1 },
        { text: "Il rugit ! Ça va être violent.", priority: 1 },
        { text: "La bête perd le contrôle !", priority: 1 },
        { text: "Tu as réveillé quelque chose de terrible." },
        { text: "Son sang bouillonne ! Attention !" },
        { text: "La fureur le consume. Et bientôt toi aussi." },
        { text: "Il charge ! Écarte-toi !" },
        { text: "Un monstre enragé est deux fois plus dangereux." },
        { text: "Sa vitesse a doublé ! Tu l'as senti ?" },
        { text: "La rage le rend plus rapide. Beaucoup plus rapide." },
        { text: "Il ne reculera pas. Pas maintenant." },
        { text: "Ses yeux sont rouges de rage." },
        { text: "Tu l'as provoqué. Assume." },
        { text: "La colère d'une bête n'a pas de limites." },
        { text: "Il fonce ! Prépare-toi au choc !" },
        { text: "Un monstre en colère est un monstre imprévisible." },
        { text: "Cours ou combats, mais décide vite !" },
    ],

    player_crouch: [
        { text: "Tu te fais petit ? Malin." },
        { text: "Mode furtif activé. Mes créatures y voient moins." },
        { text: "Rampe dans l'ombre. C'est ta meilleure option." },
        { text: "Tu te caches ? Les lâches vivent plus longtemps." },
        { text: "Discrétion... Un art que peu maîtrisent." },
        { text: "Plus bas. Encore plus bas. Les monstres regardent en haut." },
        { text: "Tu rampes dans mes entrailles. Quelle humilité." },
        { text: "Accroupi comme un prédateur. J'aime." },
        { text: "Furtif. Silencieux. Mortel." },
        { text: "Les ombres te cachent. Pour l'instant." },
        { text: "Un pas de trop et ils te repèrent." },
        { text: "La discrétion est l'arme des survivants." },
        { text: "Bien. Ils ne t'ont pas encore vu." },
        { text: "Reste bas. Le danger passe au-dessus." },
        { text: "Tu te fais tout petit dans mon grand donjon." },
        { text: "Silencieux comme une ombre." },
        { text: "La furtivité te gardera en vie." },
        { text: "Chut... Ils écoutent." },
        { text: "Tu te glisses dans mes ombres. Habile." },
        { text: "Ramper n'est pas une honte. C'est une stratégie." },
    ],

    arrow_shot: [
        { text: "Tire ! Que la flèche trouve sa cible !" },
        { text: "Un tir précis peut tout changer." },
        { text: "La flèche fend l'air de mon donjon." },
        { text: "Vise bien. Tu n'as pas de flèches infinies." },
        { text: "Le sifflement de la flèche... Musique à mes oreilles." },
        { text: "Droit au but, j'espère." },
        { text: "La flèche traverse mes couloirs." },
        { text: "Un archer dans mon donjon. Original." },
        { text: "Chaque flèche raconte une histoire." },
        { text: "Tire et prie. C'est la méthode." },
        { text: "La trajectoire est parfaite... ou pas." },
        { text: "Une flèche dans le noir. Romantique." },
        { text: "L'air siffle. La mort voyage." },
        { text: "Bon tir ! Ou pas. On verra." },
        { text: "Les flèches volent, les monstres tombent." },
        { text: "Ton arc chante la mélodie de la guerre." },
        { text: "Précision et patience. L'art de l'archer." },
        { text: "La corde vibre. Le destin tremble." },
        { text: "Que cette flèche atteigne son but." },
        { text: "Un projectile de plus dans l'obscurité." },
    ],

    spell_cast: [
        { text: "La magie résonne dans mes murs !" },
        { text: "Un sortilège ! Mes pierres vibrent." },
        { text: "Le feu magique illumine mes ténèbres." },
        { text: "Puissant. La magie est toujours impressionnante." },
        { text: "Tes flammes réchauffent mes couloirs glacés." },
        { text: "Un mage dans mon donjon. Intéressant." },
        { text: "La boule de feu traverse l'obscurité." },
        { text: "La magie ancienne s'éveille en toi." },
        { text: "Brûle-les ! Brûle-les tous !" },
        { text: "Le pouvoir arcanique à l'état pur." },
        { text: "Mes murs absorbent l'énergie magique." },
        { text: "Impressionnant. Continue comme ça." },
        { text: "Le feu danse dans mes ténèbres." },
        { text: "Ta magie éclaire ce que l'ombre cache." },
        { text: "Les flammes lèchent mes pierres." },
        { text: "Un sort bien placé vaut mille épées." },
        { text: "La magie coule en toi comme le sang dans mes murs." },
        { text: "Que le feu consume mes créatures !" },
        { text: "L'air crépite d'énergie magique." },
        { text: "Un mage puissant. Mes créatures vont souffrir." },
    ],

    all_enemies_near: [
        { text: "Ils t'encerclent ! Attention !", priority: 1 },
        { text: "Trop d'ennemis autour de toi !", priority: 1 },
        { text: "Tu es entouré ! Bouge !", priority: 1 },
        { text: "Ils convergent vers toi. Ce n'est pas bon.", priority: 1 },
        { text: "Encerclement ! Trouve une issue !", priority: 1 },
        { text: "Tous sur toi ! Ne reste pas là !", priority: 1 },
        { text: "C'est un assaut groupé ! Défends-toi !", priority: 1 },
        { text: "Ils arrivent de tous les côtés !", priority: 1 },
        { text: "La meute te cerne. Pas de panique.", priority: 1 },
        { text: "Tu es au centre de la tempête.", priority: 1 },
        { text: "Mes créatures ont fait alliance contre toi.", priority: 1 },
        { text: "Encerclé ! Un mur dans le dos, vite !", priority: 1 },
        { text: "Ils se coordonnent ! C'est mauvais signe.", priority: 1 },
        { text: "La horde t'entoure. Bats-toi ou fuis !", priority: 1 },
        { text: "Tu es pris au piège entre mes créatures !", priority: 1 },
        { text: "Trop de monstres ! Recule vers un couloir !", priority: 1 },
        { text: "Ils sentent ta peur. Ça les attire.", priority: 1 },
        { text: "L'étau se resserre autour de toi.", priority: 1 },
        { text: "C'est maintenant ou jamais. Bats-toi !", priority: 1 },
        { text: "La meute attaque en groupe. Classique mais efficace.", priority: 1 },
    ],

    player_full_hp: [
        { text: "Tu es en pleine forme. Ça ne durera pas." },
        { text: "Santé maximale. Profite de cet instant rare." },
        { text: "Tu rayonnes de vitalité. Mes monstres vont y remédier." },
        { text: "Pleine santé ? C'est presque ennuyeux." },
        { text: "Tu es au top. Parfait pour affronter le pire." },
        { text: "100% de vie. 0% de garantie de survie." },
        { text: "En pleine forme ! Mais pour combien de temps ?" },
        { text: "Ta vigueur est impressionnante." },
        { text: "Santé restaurée. Le combat peut reprendre." },
        { text: "Tu brilles de santé. Les monstres adorent les proies vigoureuses." },
        { text: "Parfait état. C'est rare ici." },
        { text: "Plein de vie. Plein d'espoir. C'est mignon." },
        { text: "Tu es prêt pour la suite. J'espère." },
        { text: "Tes blessures ont disparu. Pas les dangers." },
        { text: "En forme olympique. Le donjon approuve." },
        { text: "100% ! Un bon départ pour un mauvais plan." },
        { text: "Rechargé. Remotivé. Prêt à souffrir." },
        { text: "Ta santé est pleine. Mes pièges aussi." },
        { text: "En pleine santé dans un lieu de mort. L'ironie." },
        { text: "Tu rayonnes. Ça illumine mes sombres couloirs." },
    ],

    no_potions: [
        { text: "Plus de potions... Sois prudent.", priority: 1 },
        { text: "Ton inventaire est vide. Pas de seconde chance.", priority: 1 },
        { text: "Zéro potion. C'est maintenant que ça devient intéressant.", priority: 1 },
        { text: "Sans potions, chaque coup peut être le dernier.", priority: 1 },
        { text: "Plus de soins. Tu joues avec le feu.", priority: 1 },
        { text: "Tes poches sont vides. Tes chances aussi.", priority: 1 },
        { text: "Pas de potion de secours. Évite les dégâts.", priority: 1 },
        { text: "Tu n'as plus rien pour te soigner. Attention.", priority: 1 },
        { text: "Inventaire à sec. Chaque point de vie compte.", priority: 1 },
        { text: "Plus de remèdes. La prudence est ta seule alliée.", priority: 1 },
        { text: "Zéro potion. Le prochain coffre est ta priorité.", priority: 1 },
        { text: "Sans soins, un combat peut être fatal.", priority: 1 },
        { text: "Tu n'as plus de filet de sécurité.", priority: 1 },
        { text: "Pas de potions. Pas de marge d'erreur.", priority: 1 },
        { text: "Cherche un coffre. Ta survie en dépend.", priority: 1 },
        { text: "Inventaire vide. Stratégie : ne pas se faire toucher.", priority: 1 },
        { text: "Rien pour te soigner. Bonne chance.", priority: 1 },
        { text: "Tes réserves sont épuisées. Comme bientôt toi.", priority: 1 },
        { text: "Plus une goutte de potion. Fais avec.", priority: 1 },
        { text: "Zero potion, zéro marge. Bienvenue en mode survie.", priority: 1 },
    ],

    no_arrows: [
        { text: "Plus de flèches ! Tu vas devoir improviser.", priority: 1 },
        { text: "Carquois vide. C'est gênant pour un archer.", priority: 1 },
        { text: "Zéro flèche. Trouve un coffre, vite.", priority: 1 },
        { text: "Plus de munitions. Cours ou cache-toi.", priority: 1 },
        { text: "Ton carquois est vide comme mes salles après un massacre.", priority: 1 },
        { text: "Sans flèches, tu n'es qu'une cible facile.", priority: 1 },
        { text: "Pas de flèches ? Pas de distance de sécurité.", priority: 1 },
        { text: "Le carquois pleure sa vacuité.", priority: 1 },
        { text: "Plus rien à tirer. C'est problématique.", priority: 1 },
        { text: "Zéro flèche. Tu vas devoir être créatif.", priority: 1 },
        { text: "Ton arc est inutile sans flèches.", priority: 1 },
        { text: "Pas de munitions. Cherche un coffre.", priority: 1 },
        { text: "Un archer sans flèches... C'est un comédien.", priority: 1 },
        { text: "Le silence de ton arc est assourdissant.", priority: 1 },
        { text: "Plus de flèches. Espérons que tu sais courir.", priority: 1 },
        { text: "Carquois à sec. La situation se complique.", priority: 1 },
        { text: "Sans projectiles, ta portée est... nulle.", priority: 1 },
        { text: "Trouve des flèches ou apprends le corps-à-corps.", priority: 1 },
        { text: "Ton carquois bâille. Les monstres non.", priority: 1 },
        { text: "À court de flèches. Le prochain coffre est vital.", priority: 1 },
    ],

    multiple_kills: [
        { text: "Un massacre ! Tu es une machine de guerre !" },
        { text: "Carnage ! Mes créatures tombent comme des mouches." },
        { text: "Tu les enchaînes ! Impressionnant !" },
        { text: "Multi-kill ! Je n'avais pas vu ça depuis des lustres." },
        { text: "Tu fauches tout sur ton passage !" },
        { text: "Inarrêtable ! Tu es inarrêtable !" },
        { text: "Boucherie totale ! Mes murs en sont éclaboussés." },
        { text: "Combo mortel ! Tu es en feu !" },
        { text: "Ils tombent un par un. Non, trois par trois !" },
        { text: "Tu es déchaîné ! Rien ne t'arrête !" },
        { text: "La danse de la mort dans toute sa splendeur." },
        { text: "Un vrai guerrier. Sans pitié." },
        { text: "Le sol est jonché de cadavres. Ton œuvre." },
        { text: "Tu les extermines ! C'est... beau à voir." },
        { text: "Une tuerie. Littéralement." },
        { text: "Mes créatures n'avaient aucune chance." },
        { text: "L'ange de la mort est parmi nous." },
        { text: "Chaîne de kills ! Le donjon tremble." },
        { text: "Tu nettoies mes salles mieux qu'une tornade." },
        { text: "Dévastateur. Absolument dévastateur." },
    ],
};

/**
 * Get a random dialogue line for a given trigger type.
 * Uses weighted random if priority is set.
 */
export function getRandomDialogue(trigger: TriggerType): DialogueLine {
    const lines = COMPANION_DIALOGUES[trigger];
    const index = Math.floor(Math.random() * lines.length);
    return lines[index];
}

/**
 * Get a random dialogue text for a given trigger type.
 * Avoids repeating the last N dialogues.
 */
export function getRandomDialogueText(
    trigger: TriggerType,
    recentTexts: string[] = [],
    maxRetries: number = 5
): string {
    const lines = COMPANION_DIALOGUES[trigger];

    for (let i = 0; i < maxRetries; i++) {
        const index = Math.floor(Math.random() * lines.length);
        const text = lines[index].text;
        if (!recentTexts.includes(text)) {
            return text;
        }
    }

    // Fallback: just return any random one
    return lines[Math.floor(Math.random() * lines.length)].text;
}
